[functions.create-order]
verify_jwt = true

[functions.confirm-order-files]
verify_jwt = true

[functions.verify-admin-access]
verify_jwt = false

[functions.create-payment-session]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.admin-order-action]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false