-- This migration intentionally performs no database changes.
--
-- The canonical project finance and part-payment schema is defined in
-- 20260823195119_project_finance_payment_plans.sql. An earlier draft of this
-- migration attempted to recreate those tables with incompatible column names
-- (project_id/requested_amount instead of order_id/approved_amount_kobo), which
-- made a fresh migration run fail. It is retained as a no-op so the migration
-- timestamp remains stable for environments that already recorded it.
