-- This migration intentionally performs no database changes.
--
-- The complete, secured project finance system is defined in
-- 20260823195119_project_finance_payment_plans.sql. This file previously
-- duplicated a draft schema and policies that conflicted with the canonical
-- order_id-based part-payment model. Keeping this timestamp as a documented
-- no-op preserves migration history while allowing clean database rebuilds.
